markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
include:  
  - _redirects
api:
  core: 'https://api.freesewing.org'
  data: 'http://data.freesewing.org'
