content:
  - docs
  - blog
  - showcase
defaults:
  repos:
    core: 'https://github.com/freesewing/core'
    data: 'https://github.com/freesewing/data'
    site: 'https://github.com/freesewing/site'
    tile: 'https://github.com/freesewing/tile'
  sa:
    custom: 1
    imperial: 0.625
    metric: 1
  scale:
    imperial: 25.4
    metric: 10
  step:
    imperial: 0.125
    metric: 0.1
  themes:
    - Classic
    - Paperless
i18n:
  coordinators:
    de: manufaktur.edelweiss
    en: joost
    es: AlfaLyer
    fr: MrsMonkey
    nl: AnnekeCaramin
    'no': _vacant
  files:
    - app
    - i18n
    - measurements
    - options
    - optiongroups
    - patterns
  locales:
    disabled:
      - de
      - fr
      - 'no'
    enabled:
      - en
      - es
      - nl
  origin: en
  stats:
    de:
      app: 0
      blog: 0
      docs: 0
      i18n: 0
      measurements: 0
      optiongroups: 0
      options: 0
      patterns: 36
      showcase: 0
    en:
      app: 300
      blog: 28
      docs: 9
      i18n: 6
      measurements: 26
      optiongroups: 12
      options: 302
      patterns: 37
      showcase: 51
    es:
      app: 279
      blog: 0
      docs: 0
      i18n: 6
      measurements: 26
      optiongroups: 12
      options: 0
      patterns: 37
      showcase: 0
    fr:
      app: 77
      blog: 0
      docs: 0
      i18n: 0
      measurements: 25
      optiongroups: 0
      options: 0
      patterns: 4
      showcase: 0
    nl:
      app: 299
      blog: 2
      docs: 2
      i18n: 6
      measurements: 26
      optiongroups: 12
      options: 302
      patterns: 37
      showcase: 1
    'no':
      app: 0
      blog: 0
      docs: 0
      i18n: 0
      measurements: 25
      optiongroups: 0
      options: 0
      patterns: 0
      showcase: 0
    xx:
      app: 0
      blog: 0
      docs: 0
      i18n: 0
      measurements: 0
      optiongroups: 0
      options: 0
      patterns: 0
      showcase: 0
  target:
    app: 300
    blog: 28
    docs: 9
    i18n: 6
    measurements: 26
    optiongroups: 12
    options: 302
    patterns: 37
    showcase: 51
  template: xx
ui:
  darkToolbar: false
