url: 'https://joost.beta.freesewing.org/'
github: 'https://github.com/freesewing'
twitter: 'freesewing_org'
instagram: 'freesewing_org'
gitter: 'https://gitter.im/freesewing/freesewing'

api:
  core: 'https://joost.api.freesewing.org'
  data: 'https://joost.data.freesewing.org'

markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
include:  
  - _redirects
  - apigen

collections:
    posts:
        output: true
        permalink: /blog/:title/
    showcases:
        output: true
        permalink: /showcase/:title/
        layout: showcase
gems:
    - jekyll-assets

assets:
  compress:
    css: true
    js:  true

  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  sources:
    - _assets/css
    - _assets/fonts
    - _assets/img
    - _assets/js

  features:
    liquid: false
    integrity: false
    automatic_img_size: true
    automatic_img_alt : true
